include: package:dart_flutter_team_lints/analysis_options.yaml

analyzer:
  errors:
    # Temporary due to https://github.com/schultek/jaspr/issues/400
    prefer_const_constructors: ignore
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

linter:
  rules:
    - discarded_futures
    - document_ignores
    - eol_at_end_of_file
    - implicit_reopen
    - missing_code_block_language_in_doc_comment
    - no_literal_bool_comparisons
    - no_self_assignments
    - prefer_asserts_with_message
    #- prefer_const_constructors
    - prefer_const_declarations
    - prefer_const_literals_to_create_immutables
    - prefer_final_fields
    - prefer_final_in_for_each
    - prefer_final_locals
    - prefer_relative_imports
    - strict_top_level_inference
    - unnecessary_breaks
    - unnecessary_null_aware_operator_on_extension_on_nullable
    - unnecessary_underscores
    - use_enums
    - use_truncating_division
