name: dart_site_in_dart
description: Building the dart.dev site in Dart.
publish_to: none

environment:
  sdk: ^3.7.0

dependencies:
  fbh_front_matter: ^0.0.1
  jaspr: ^0.18.0
  jaspr_router: ^0.6.4
  liquify: ^0.8.2
  markdown: ^7.3.0
  path: ^1.9.1
  watcher: ^1.1.1

dev_dependencies:
  build_runner: ^2.4.15
  build_web_compilers: ^4.1.2
  dart_flutter_team_lints: ^3.4.0
  jaspr_builder: ^0.18.0

jaspr:
  mode: static

