name: deploy

on:
  # Run on PRs and pushes to the default branch.
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 0 * * 0"

# Declare default permissions as read only.
permissions: read-all

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - uses: dart-lang/setup-dart@e51d8e571e22473a2ddebf0ef8a2123f0ab2c02c
      - name: Fetch Dart packages
        run: dart pub get
      - name: Build site
        run: dart run jaspr_cli:jaspr build --optimize 3
      - name: Deploy to Cloudflare pages
        uses: cloudflare/wrangler-action@392082e81ffbcb9ebdde27400634aa004b35ea37
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy build/jaspr --project-name=dart-site-in-dart
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
